package harness

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Pi support.
//
// Pi (github.com/earendil-works/pi, MIT) is a minimal open-source coding
// agent that runs GPT-6 Astra through an OpenAI API key or a ChatGPT/Codex
// subscription, alongside most other providers.
//
// Pi needs far less glue than OpenCode:
//
//   - `pi --continue` resumes the most recent session for the exact working
//     directory (sessions live in ~/.pi/agent/sessions/--<encoded cwd>--/), so
//     it is already per-worktree, and it starts a fresh session when there is
//     none. A trailing positional message is submitted on resume too.
//   - `--append-system-prompt <file>` reads the prompt from a file, so ccmux's
//     system prompt stays out of argv (see SystemPromptFileBlock), and Pi
//     re-reads it on every launch, so a resumed session gets the refreshed one.
//   - `-e <file>` loads an extension for this run only. The ccmux extension
//     stands in for Claude Code's hooks: `ccmux agent-stopped` on
//     `agent_settled` (Pi will not continue on its own; after retries and
//     compaction) and `ccmux ci-wait` after a bash `gh pr create` /
//     `git push`.
//
// Launches still go through a small `ccmux run-pi` wrapper, because the
// extension file has to be written and the model flag is conditional — both
// awkward to express inside the one-line commands the launcher scripts embed.
//
// Pi has no per-tool approval prompts. It does ask whether to trust a
// project's own .pi extensions and settings before loading them; ccmux passes
// --approve, the counterpart of pre-trusting the worktree for Claude Code
// and Codex, so an agent never stalls on that dialog with nobody watching.

// PiDefaultModel is the model ccmux asks Pi for when the user has not chosen
// one: GPT-6 Astra on the OpenAI API provider. ChatGPT-subscription logins use
// Pi's "openai-codex" provider instead — set PiModelEnv to
// "openai-codex/gpt-6-astra" for that.
const PiDefaultModel = "openai/gpt-6-astra"

// PiModelEnv overrides PiDefaultModel. Set it to another provider/model id
// (Pi's ":<thinking>" suffix works too), or to the empty string to pass no
// --model and let Pi's own settings pick.
const PiModelEnv = "CCMUX_PI_MODEL"

// PiModel returns the model the wrapper passes to `pi --model`, or "" to defer
// to Pi's settings.
func PiModel() string {
	if v, ok := os.LookupEnv(PiModelEnv); ok {
		return strings.TrimSpace(v)
	}
	return PiDefaultModel
}

// piExtensionPath is where the wrapper writes the extension. Shared by every
// agent and rewritten when ccmux's copy changes.
func piExtensionPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".ccmux", "pi", "ccmux-extension.js"), nil
}

// PreparePiLaunch writes the extension and assembles pi's argv. cont resumes
// the worktree's latest Pi session (or starts fresh when there is none);
// prompt is the first message, submitted either way.
func PreparePiLaunch(agentID string, cont bool, prompt string) ([]string, error) {
	extPath, err := piExtensionPath()
	if err != nil {
		return nil, err
	}
	if err := writeFileIfChanged(extPath, []byte(PiExtensionJS), 0o644); err != nil {
		return nil, fmt.Errorf("failed to write the ccmux Pi extension: %w", err)
	}

	args := []string{"pi", "--approve", "--extension", extPath}
	if model := PiModel(); model != "" {
		args = append(args, "--model", model)
	}
	if cont {
		args = append(args, "--continue")
	}
	if agentID != "" {
		if p, err := systemPromptFile(agentID); err == nil {
			if _, statErr := os.Stat(p); statErr == nil {
				args = append(args, "--append-system-prompt", p)
			}
		}
	}
	if prompt != "" {
		// "--" so a message starting with "-" is not parsed as a flag.
		args = append(args, "--", prompt)
	}
	return args, nil
}

// PiExtensionJS is the Pi extension ccmux installs at
// ~/.ccmux/pi/ccmux-extension.js. It is inert unless CCMUX_AGENT_ID is set.
const PiExtensionJS = `// ccmux Pi extension. Generated by ccmux and rewritten when ccmux's copy
// changes; edits here are lost. See internal/harness/pi.go.
import { spawn } from "node:child_process"

const AGENT_ID = process.env.CCMUX_AGENT_ID || ""

// Fire-and-forget: a ccmux call must never block or fail the agent's turn.
function ccmux(args) {
  try {
    const child = spawn("ccmux", args, { detached: true, stdio: "ignore" })
    child.on("error", () => {})
    child.unref()
  } catch {}
}

const PR_CREATE = /(^|[\s&;|(])gh\s+pr\s+create(\s|$)/
const GIT_PUSH = /(^|[\s&;|(])git\s+push(\s|$)/
const PR_URL = /https:\/\/github\.com\/[^\s]+\/pull\/[0-9]+/g

export default function (pi) {
  if (!AGENT_ID) return

  // agent_settled: Pi has finished the run and will not continue on its own
  // (retries, compaction and queued messages are already done) — the
  // counterpart of Claude Code's Stop hook.
  pi.on("agent_settled", async () => {
    ccmux(["agent-stopped", AGENT_ID])
  })

  pi.on("tool_result", async (event) => {
    if (!event || event.toolName !== "bash") return
    const command = String((event.input && event.input.command) || "")
    if (PR_CREATE.test(command)) {
      const text = (event.content || [])
        .filter((c) => c && c.type === "text")
        .map((c) => c.text)
        .join("\n")
      const urls = text.match(PR_URL)
      if (urls) ccmux(["ci-wait", urls[urls.length - 1]])
      return
    }
    if (GIT_PUSH.test(command)) ccmux(["ci-wait"])
  })
}
`
